// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Image1;
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_1366475832);    // assets/battery-medium-custom.png
LV_IMG_DECLARE(ui_img_150891397);    // assets/battery-low-custom.png
LV_IMG_DECLARE(ui_img_446092942);    // assets/battery-high-custom1.png
LV_IMG_DECLARE(ui_img_1120861132);    // assets/power-plug-outline-custom.png
LV_IMG_DECLARE(ui_img_1124193684);    // assets/power-plug-off-outline-custom.png
LV_IMG_DECLARE(oshw_logo);



LV_FONT_DECLARE(ui_font_FontHighL1);
LV_FONT_DECLARE(ui_font_FontHighL2);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
